apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hellopyjob
spec:
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 4
  failedJobsHistoryLimit: 4
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: pyhelloc
            image: hellopy:roshanf
            imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure